# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Week09-2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Week09-2
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  # Pods for KakaoLogin
end
